# Strategy Types (enforce via database constraint)
strategy_types:
  - news
  - secondary
  - orderflow_off_open
  - breakout_breakdown
  - swing
  - curl
  - roll
  - orderflow
  - earnings
  - ipo
  - waterfall

# Analysis Timeframes (minutes)
timeframes: [3, 5, 10, 15, 30, 60, 120, 240]

# Validation Rules
validation:
  max_reasonable_drawdown_pct: -50.0
  min_trade_duration_seconds: 60
  max_trade_duration_hours: 24
  max_size_min: 1
  max_size_max: 1000000

# CSV Import Settings
csv_import:
  default_strategy_type: "news"  # If not provided in CSV
  date_format: "%Y-%m-%d %H:%M:%S"
  timezone: "America/New_York"
  delimiter: "|"

# Polygon Data Fetching Settings
polygon_data:
  # Default granularity for fetching market data
  # Options: 'minute', 'second', 'tick'
  # - minute: Good for free tier, general analysis (390 bars/trade)
  # - second: Best balance of precision and efficiency (23,400 bars/trade) - Requires Starter+
  # - tick: Maximum precision (varies, can be 100k+ ticks/trade) - Requires Developer+
  default_granularity: "minute"

  # Whether to automatically upgrade to more granular data if available
  auto_upgrade_granularity: false

  # Maximum ticks to fetch per request
  max_ticks_per_request: 50000

  # Cache TTL for different data types (hours)
  cache_ttl:
    minute: 24   # Minute bars cached for 24 hours
    second: 24   # Second bars cached for 24 hours
    tick: 12     # Tick data cached for 12 hours (more volatile)
